In [3]:
import sys
print('python', sys.version)

import numpy as np
print('numpy', np.__version__)

import pandas as pd
print('pandas', pd.__version__)

# 결과 확인을 용이하게 하기 위한 코드
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
numpy 1.20.3
pandas 1.4.1


## comparison (Cont'd)

### 연습

In [4]:
a1=np.arange(5)
a1
np.sum(a1%3==0)

array([0, 1, 2, 3, 4])

2

In [5]:
a1=np.random.randint(100, size=8)
a1
a2=(a1%3==0)
a3=(a1>30)

a2&a3
a2|a3

array([ 5,  6, 42, 28, 93, 86, 56, 49])

array([False, False,  True, False,  True, False, False, False])

array([False,  True,  True, False,  True,  True,  True,  True])

In [7]:
a1=np.random.randint(100, size=(3,4))
a2=a1>50
a3=a1<80

a1
a2
a3
a2&a3

array([[24, 95, 19, 13],
       [47, 75,  4, 37],
       [66, 30, 55, 46]])

array([[False,  True, False, False],
       [False,  True, False, False],
       [ True, False,  True, False]])

array([[ True, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

array([[False, False, False, False],
       [False,  True, False, False],
       [ True, False,  True, False]])

In [9]:
a1=np.random.randint(100, size=(3,4))
a1

a2=a1>50
a2
~a2
a2==False

array([[30, 11, 86, 58],
       [69, 69,  9, 15],
       [72, 69,  6,  2]])

array([[False, False,  True,  True],
       [ True,  True, False, False],
       [ True,  True, False, False]])

array([[ True,  True, False, False],
       [False, False,  True,  True],
       [False, False,  True,  True]])

array([[ True,  True, False, False],
       [False, False,  True,  True],
       [False, False,  True,  True]])

### 실습1

In [232]:
a1=np.arange(4,41,4)
a1
a2=a1*a1
a2
a2%6
np.sum((a2%6)==0)

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

array([  16,   64,  144,  256,  400,  576,  784, 1024, 1296, 1600])

array([4, 4, 0, 4, 4, 0, 4, 4, 0, 4], dtype=int32)

3

### 실습2

In [84]:
a1=np.random.randint(1,11, size=(3,3))
a1
(a1!=6)&(a1%3==0)
np.sum((a1!=6)&(a1%3==0))

array([[ 3,  9,  5],
       [ 3, 10,  6],
       [ 7,  3,  5]])

array([[ True,  True, False],
       [ True, False, False],
       [False,  True, False]])

4

## np.nan & np.where

### 연습

In [13]:
a1=np.array([1,np.nan,2,np.nan,3])
a1

## nan: false, value: true
a1==a1
~np.isnan(a1)

## nan: true, value: false
a1!=a1
np.isnan(a1)

## 동작하지 않음
a1==np.nan

array([ 1., nan,  2., nan,  3.])

array([ True, False,  True, False,  True])

array([ True, False,  True, False,  True])

array([False,  True, False,  True, False])

array([False,  True, False,  True, False])

array([False, False, False, False, False])

In [16]:
a1=np.array([100,200,-2])
a1
np.where(a1>0,3,2)

array([100, 200,  -2])

array([3, 3, 2])

In [23]:
a1=np.random.randint(100, size=5)
a1
a2=np.where(a1>50)
a2
type(a2)
ind=a2[0]
ind
ind[0]

array([21, 86, 22, 55,  5])

(array([1, 3], dtype=int64),)

tuple

array([1, 3], dtype=int64)

1

In [28]:
a=np.arange(100,110).reshape(2,5)
a
b=np.where(a%2==0)
b
b[0]
b[1]
list(zip(b[0],b[1]))

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109]])

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 2, 4, 1, 3], dtype=int64))

array([0, 0, 0, 1, 1], dtype=int64)

array([0, 2, 4, 1, 3], dtype=int64)

[(0, 0), (0, 2), (0, 4), (1, 1), (1, 3)]

### 실습3

In [33]:
#### 1
a1=np.random.randint(1,11,size=(5,5))
a1
b1=np.where(a1>=7)

s1=0
for ii,jj in zip(b1[0], b1[1]):
    s1+=a1[ii,jj]
s1

array([[ 7,  9,  6,  8,  2],
       [ 6,  3,  7,  5,  4],
       [ 3,  6, 10,  9,  8],
       [10,  6,  2, 10,  6],
       [ 4,  2,  8,  8,  5]])

94

In [39]:
#### 2
a1=np.random.randint(1,11,size=(5,5))
a1
b1=np.where((a1>=7)&(a1%2==0))

s1=0
for ii,jj in zip(b1[0], b1[1]):
    a1[ii,jj]
    s1+=a1[ii,jj]
s1

array([[10,  9,  8,  1,  5],
       [ 1,  9,  9,  1,  9],
       [ 2,  1,  2,  3, 10],
       [10,  3,  1,  9,  2],
       [ 8,  4,  7,  2,  7]])

10

8

10

10

8

46

## boolean index

### 연습

In [40]:
a1=np.random.randint(1,11,size=(4,4))
a1
a1<=3
a1[a1<=3]

array([[10,  7, 10,  3],
       [ 1,  7,  8,  7],
       [ 5,  6,  1,  2],
       [ 3,  6,  2,  6]])

array([[False, False, False,  True],
       [ True, False, False, False],
       [False, False,  True,  True],
       [ True, False,  True, False]])

array([3, 1, 1, 2, 3, 2])

In [41]:
a1=np.random.randint(1,11,size=(4,4))
a1
a1[(a1%3)!=0]

array([[ 8,  9,  1,  5],
       [ 7, 10,  8,  1],
       [10,  6,  8,  8],
       [ 5,  2, 10, 10]])

array([ 8,  1,  5,  7, 10,  8,  1, 10,  8,  8,  5,  2, 10, 10])

In [43]:
a1=np.random.randint(1,11,size=(3,4))
a2=np.random.randint(1,11,size=(3,4))
a1
a1>8
a2
a2[a1>8]

array([[ 1,  5,  8,  5],
       [10,  3,  7,  8],
       [10,  6,  9, 10]])

array([[False, False, False, False],
       [ True, False, False, False],
       [ True, False,  True,  True]])

array([[ 7, 10,  1,  5],
       [ 8,  9,  9,  7],
       [ 1,  5, 10,  8]])

array([ 8,  1, 10,  8])

In [2]:
a1=np.random.randint(100,size=(4,4))

# 조건에 맞는 행 선택
b1=(a1[:,3]%3==0)
b1
a1[b1,:]

# 조건에 맞는 열 선택
b2=(a1[0,:]>50)
b2
a1[:, b2]

array([False,  True, False, False])

array([[87, 27,  5, 30]])

array([ True, False,  True,  True])

array([[85, 97, 91],
       [87,  5, 30],
       [24, 30,  1],
       [27, 27, 11]])

### 실습4

In [3]:
a1=np.arange(24).reshape(6,4)
a1
a2=a1[:,-1]
a2
b1=(a2%3==0)|(a2>10)
b1
a2[b1]
a2[b1].sum()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

array([ 3,  7, 11, 15, 19, 23])

array([ True, False,  True,  True,  True,  True])

array([ 3, 11, 15, 19, 23])

71

### 실습5

In [5]:
a1=np.random.randint(10, size=(5,5))
a1
b1=a1[:,-1]>5
b1
a2=a1[b1,:]
a2
a2.mean(axis=1)

array([[3, 2, 8, 2, 0],
       [9, 0, 5, 7, 8],
       [7, 4, 0, 8, 8],
       [3, 8, 3, 5, 7],
       [2, 3, 0, 6, 6]])

array([False,  True,  True,  True,  True])

array([[9, 0, 5, 7, 8],
       [7, 4, 0, 8, 8],
       [3, 8, 3, 5, 7],
       [2, 3, 0, 6, 6]])

array([5.8, 5.4, 5.2, 3.4])

### 실습6

In [8]:
m1=np.random.randint(10, size=10)
e1=np.random.randint(10, size=10)
m1
e1

## 1)
b1=m1<e1
b1
np.sum(b1)

## 2)
m1[b1]
m1[b1].mean()

array([4, 1, 3, 2, 0, 4, 3, 3, 7, 3])

array([7, 6, 7, 7, 8, 3, 8, 9, 2, 6])

array([ True,  True,  True,  True,  True, False,  True,  True, False,
        True])

8

array([4, 1, 3, 2, 0, 3, 3, 3])

2.375

## fancy index

### 연습

In [9]:
a1=np.array([1,2,3,4])
index=np.array([0,0,3,2])
a1[index]

array([1, 1, 4, 3])

In [1]:
a1=np.random.randint(100, size=(4,5))
a1
a1[[0,1,2],[2,3,2]]

array([80, 17,  9])

In [6]:
## 조건에 맞는 element 가져오는 방법
a1=np.random.randint(100, size=(4,5))

## boolean index 사용하는 경우 (가장 간단)
a1[a1>70] 

## np.where를 사용하는 경우
b1=np.where(a1>70)

##### fancy index 사용
a1[b1]

##### fancy index 사용하지 않는 경우
l2=[]
for ii,jj in zip(b1[0], b1[1]):
    l2.append(a1[ii,jj])
l2

array([85, 91, 99, 84, 78, 73, 85])

array([85, 91, 99, 84, 78, 73, 85])

[85, 91, 99, 84, 78, 73, 85]

### 실습7

In [215]:
p1=np.array([1000,2000,1500,2000])
p1
o1=np.array([1,1,3,2,2,3,4,1])
p1[o1-1]
p1[o1-1].sum()

array([1000, 2000, 1500, 2000])

array([1000, 1000, 1500, 2000, 2000, 1500, 2000, 1000])

12000

### 실습8

In [7]:
a1=np.random.randint(10,size=(6,4))
a1=a1.astype(float)
a1[[0,1,1,3],[1,1,2,3]]=np.nan
a1
np.isnan(a1)
a2=np.isnan(a1).sum(axis=1)
b1=(a2==0)
a1[b1,:]


array([[ 5., nan,  0.,  5.],
       [ 2., nan, nan,  5.],
       [ 8.,  0.,  3.,  8.],
       [ 9.,  6.,  9., nan],
       [ 4.,  2.,  6.,  1.],
       [ 0.,  5.,  8.,  0.]])

array([[False,  True, False, False],
       [False,  True,  True, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

array([[8., 0., 3., 8.],
       [4., 2., 6., 1.],
       [0., 5., 8., 0.]])

## 문제모음

### 문제1

In [10]:
a1=np.random.randint(10,size=(6,4))
a1=a1.astype(float)
a1[[0,2,2,5],[1,1,3,3]]=np.nan
a1

array([[ 7., nan,  1.,  0.],
       [ 8.,  6.,  2.,  5.],
       [ 7., nan,  4., nan],
       [ 7.,  2.,  5.,  9.],
       [ 3.,  5.,  8.,  2.],
       [ 7.,  0.,  1., nan]])

In [11]:
b1=np.isnan(a1)
b1
a2=b1.sum(axis=0)
a2
b2=(a2==0)
b2
a1[:,b2]
a1[:,b2].min(axis=0)

array([[False,  True, False, False],
       [False, False, False, False],
       [False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

array([0, 2, 0, 2])

array([ True, False,  True, False])

array([[7., 1.],
       [8., 2.],
       [7., 4.],
       [7., 5.],
       [3., 8.],
       [7., 1.]])

array([3., 1.])

### 문제2

In [12]:
a1=np.random.randint(10,size=(3,5))
a1

m1=a1[0,:]
e1=a1[1,:]
g1=a1[2,:]
m1>e1

g1[m1>e1]
g1[m1>e1].sum()

array([[9, 7, 7, 1, 6],
       [6, 6, 8, 8, 5],
       [2, 3, 4, 4, 5]])

array([ True,  True, False, False,  True])

array([2, 3, 5])

10

### 문제3

In [66]:
m1=np.random.randint(1,11,size=(3,4))
m1
m=m1.mean(axis=0)
m
np.sum(m1>m, axis=0)

array([[9, 1, 1, 5],
       [2, 1, 5, 9],
       [5, 7, 8, 1]])

array([5.33333333, 3.        , 4.66666667, 5.        ])

array([1, 1, 2, 1])

### 문제4

In [68]:
m1=np.random.randint(1,11,size=(3,4))
m1
m=m1.mean(axis=0)
s=m1.std(axis=0)
m
s
d=m-s
np.sum(m1>d, axis=0)

array([[ 6,  9,  5,  5],
       [ 2,  4,  6, 10],
       [ 2,  6,  4,  4]])

array([3.33333333, 6.33333333, 5.        , 6.33333333])

array([1.88561808, 2.05480467, 0.81649658, 2.62466929])

array([3, 2, 2, 3])