In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# 결과 확인을 용이하게 하기 위한 코드
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [4]:
ar1=np.array([1,2,3,4,5])
ar1
type(ar1)
ar1.dtype
ar1.shape
ar1.ndim
ar1.size
ar1.nbytes

array([1, 2, 3, 4, 5])

numpy.ndarray

dtype('int32')

(5,)

1

5

20

In [6]:
a1=np.array([1.1,2.2,3.3])
type(a1)
a1.dtype
a1.shape
a1.ndim
a1.size
a1.nbytes

numpy.ndarray

dtype('float64')

(3,)

1

3

24

In [13]:
a2=np.array([1,2,3,4],dtype=float)
a2
a2.dtype
m1=np.array([[1,2,3,4],[5,6,7,8]],np.float64)
m1.dtype
m1.shape
m1.ndim
m1.size
m1.nbytes

array([1., 2., 3., 4.])

dtype('float64')

dtype('float64')

(2, 4)

2

8

64

In [10]:
ar1=np.array([1,2,3,4.5],dtype=int)
ar1
ar1.dtype

ar2=np.array([1,2,3,4,5],dtype=float)
ar2
ar2.dtype

ar3=np.array([1,2,3,'a'],dtype=int)
ar3
ar3.dtype

array([1, 2, 3, 4])

dtype('int32')

array([1., 2., 3., 4., 5.])

dtype('float64')

ValueError: invalid literal for int() with base 10: 'a'

In [15]:
m1=np.array([[1,2,3,4],[5,6,7,8]])
m1
m1.shape
m2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
t1=np.array([m2,m2])
t1
t1.shape

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

(2, 4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

(2, 3, 4)

### 실습1

In [14]:
a1=np.array([[6,5,4],[3,2,1]],dtype=int)
a2=np.array([[6,5,4],[3,2,1]],dtype=np.float16)
a1.shape
a1.size
a1.dtype
a1.nbytes

a2.shape
a2.size
a2.dtype
a2.nbytes

(2, 3)

6

dtype('int32')

24

(2, 3)

6

dtype('float16')

12

In [15]:
a1=np.array([6,5,4],np.int32)
a1
a1.shape
a1.size
a1.dtype
a1.nbytes
a2=np.array([3,2,1],np.float16)
a2
a2.shape
a2.size
a2.dtype
a2.nbytes

array([6, 5, 4])

(3,)

3

dtype('int32')

12

array([3., 2., 1.], dtype=float16)

(3,)

3

dtype('float16')

6

In [16]:
ar1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]).reshape(6,2)
ar1
ar2=ar1.reshape(-1,6) # 전체 사이즈가 6으로 나누어 떨어져야 가능!
ar2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [17]:
a1=np.array([[2,3,4],[5,6,7],[8,9,10]]).reshape(9,1)
a1
a2=a1.reshape(-1,9)
a2


array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [28]:
ar1=np.array([[1,2,3,4],[5,6,7,8]])
ar2=ar1.reshape(8,) # vector 형태
ar2
ar3=ar1.reshape(1,8) # matrix 형태
ar3

array([1, 2, 3, 4, 5, 6, 7, 8])

array([[1, 2, 3, 4, 5, 6, 7, 8]])

### 실습3

In [33]:
v1=np.array([1,2,3,4,5,6])
v1
v1.reshape(2,3)
v1.reshape(3,2)
v1.reshape(6,1)

array([1, 2, 3, 4, 5, 6])

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [18]:
v1=np.array([1,2,3,4,5,6])
v1
v1.reshape(2,3)
v1.reshape(3,2)
v1.reshape(6,1)


array([1, 2, 3, 4, 5, 6])

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [22]:
ar1=np.array([[1,2,3,4]*3],np.int16).reshape(3,2,2)
ar1
ar1.dtype
ar2=np.arr

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]], dtype=int16)

dtype('int16')