In [1]:
import sys
print('python', sys.version)

import numpy as np
print('numpy', np.__version__)

import pandas as pd
print('pandas', pd.__version__)

# 결과 확인을 용이하게 하기 위한 코드
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
numpy 1.20.3
pandas 1.3.4


In [2]:
ar1=np.array(range(4))
ar1
ar2=np.array(range(4,12))
ar2
ar3=np.array(range(4,12,2))
ar3

array([0, 1, 2, 3])

array([ 4,  5,  6,  7,  8,  9, 10, 11])

array([ 4,  6,  8, 10])

In [4]:
a1=np.array(range(5))
a1
a2=np.array(range(5,10))
a2
a3=np.array(range(5,10,2))
a3

array([0, 1, 2, 3, 4])

array([5, 6, 7, 8, 9])

array([5, 7, 9])

In [11]:
m1=np.array(range(1,13,2)).reshape(3,2)
m1

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [16]:
m1=np.arange(0,12,2).reshape(3,2)
m1

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

### 실습1

In [5]:
t1=np.arange(1,61).reshape(5,3,4)
t1
t2=t1.flatten()
t2
t1.reshape(1,60)
t2.reshape(-1,10)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60]]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [8]:
a1=np.arange(1,61).reshape(5,3,4)
a1
a2=a1.reshape(60,)
a2
a1.reshape(1,60)
a2.reshape(-1,10)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60]]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [32]:
ar1=np.arange(12).reshape(3,4)
ar1
ar1[1,2]
ar2=np.arange(12).reshape(2,3,2)
ar2
ar2[0,1,1]=100
ar2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

6

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

array([[[  0,   1],
        [  2, 100],
        [  4,   5]],

       [[  6,   7],
        [  8,   9],
        [ 10,  11]]])

### 실습2

In [9]:
a1=np.arange(15).reshape(3,5)
a1
a1[1,3]=1000
a1

a2=np.arange(60).reshape(6,2,5)
a2
a2[3,0,4]=1000
a2
a2[::2,::3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[   0,    1,    2,    3,    4],
       [   5,    6,    7, 1000,    9],
       [  10,   11,   12,   13,   14]])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]],

       [[  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19]],

       [[  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29]],

       [[  30,   31,   32,   33, 1000],
        [  35,   36,   37,   38,   39]],

       [[  40,   41,   42,   43,   44],
        [  45,   46,   47,   48,   49]],

       [[  50,   51,   52,   53,   54],
        [  55,   56,   57,   58,   59]]])

array([[[ 0,  1,  2,  3,  4]],

       [[20, 21, 22, 23, 24]],

       [[40, 41, 42, 43, 44]]])

In [14]:
a1=np.arange(15).reshape(3,5)
a1[1,3]=1000
a1
a2=np.arange(60).reshape(6,2,5)
a2[3,0,4]=1000
a2

array([[   0,    1,    2,    3,    4],
       [   5,    6,    7, 1000,    9],
       [  10,   11,   12,   13,   14]])

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]],

       [[  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19]],

       [[  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29]],

       [[  30,   31,   32,   33, 1000],
        [  35,   36,   37,   38,   39]],

       [[  40,   41,   42,   43,   44],
        [  45,   46,   47,   48,   49]],

       [[  50,   51,   52,   53,   54],
        [  55,   56,   57,   58,   59]]])

In [15]:
m1=np.arange(16).reshape(4,4)
m1
m1[0:-2,1:]=np.arange(6).reshape(2,3)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 0,  0,  1,  2],
       [ 4,  3,  4,  5],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 실습3

In [16]:
t1=np.arange(24).reshape(4,6)
t1
t2=t1[2:,1:4]
t2
t1[2:,1:4]=np.array([-1,-2,-3,-4,-5,-6]).reshape(2,3)
t1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

array([[13, 14, 15],
       [19, 20, 21]])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, -1, -2, -3, 16, 17],
       [18, -4, -5, -6, 22, 23]])

In [18]:
a1=np.arange(24).reshape(4,6)
a1
a2=a1[2:,1:-2]
a2
a1[2:,1:-2]=np.array([-1,-2,-3,-4,-5,-6]).reshape(2,3)
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

array([[13, 14, 15],
       [19, 20, 21]])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, -1, -2, -3, 16, 17],
       [18, -4, -5, -6, 22, 23]])

### 실습4

In [19]:
a1=np.arange(24).reshape(2,12)
a1
a1[:,::4]
a2=np.arange(0,21,4).reshape(2,3)
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

array([[ 0,  4,  8],
       [12, 16, 20]])

array([[ 0,  4,  8],
       [12, 16, 20]])

In [21]:
a1=np.arange(24).reshape(2,12)
a1
a1[:,::4]
a2=np.arange(0,24,4).reshape(2,3)
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

array([[ 0,  4,  8],
       [12, 16, 20]])

array([[ 0,  4,  8],
       [12, 16, 20]])

In [22]:
a1=np.arange(50,59).reshape(3,3)
a1
np.diag(a1)

array([[50, 51, 52],
       [53, 54, 55],
       [56, 57, 58]])

array([50, 54, 58])

In [23]:
a1=np.arange(30).reshape(5,6)
a1
np.diag(a1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

array([ 0,  7, 14, 21, 28])

In [59]:
a1=np.random.randint(0,4,size=(4,5))
a1
a2=np.random.uniform(0,4,size=(4,5))
a2
a3=np.random.normal(10,5,size=(4,5))
a3
a4=np.random.choice(np.arange(10),size=(4,5))
a4

array([[2, 2, 3, 3, 1],
       [2, 2, 0, 1, 0],
       [3, 3, 2, 3, 0],
       [1, 0, 3, 2, 0]])

array([[2.04164264, 1.64149258, 2.19234115, 2.35166298, 3.57779925],
       [0.02054728, 0.69315168, 3.6660396 , 0.80361737, 2.05895295],
       [2.41873526, 0.53018396, 2.24141503, 0.49079325, 0.12609585],
       [0.25927571, 2.03112289, 2.55152146, 3.35509761, 3.42283368]])

array([[-1.09648551,  5.76700313, 12.04747616,  9.27603324, 12.4100576 ],
       [11.95438896, 12.77689125, 14.41187288,  5.44719394, 11.81469504],
       [12.45448542,  8.02116691, 17.79714876,  3.91525282,  9.73608559],
       [14.92318921, 19.22490753, 15.64750611, 12.16313754, 11.36741218]])

array([[0, 5, 9, 9, 5],
       [6, 3, 5, 8, 3],
       [6, 4, 8, 0, 8],
       [7, 8, 7, 9, 2]])

### 실습5

In [24]:
a1=np.zeros(shape=(4,4),dtype=np.int8)
a1[1,:]=np.array([2,2,2,2])
a1[:,2]=np.array([4,4,4,4])
a1

array([[0, 0, 4, 0],
       [2, 2, 4, 2],
       [0, 0, 4, 0],
       [0, 0, 4, 0]], dtype=int8)

In [25]:
a1=np.zeros(shape=(4,4),dtype=np.int8)
a1[1,:]=np.array([2,2,2,2])
a1[:,2]=np.array([4,4,4,4])
a1

array([[0, 0, 4, 0],
       [2, 2, 4, 2],
       [0, 0, 4, 0],
       [0, 0, 4, 0]], dtype=int8)

### 실습6

In [26]:
a1=np.random.normal(loc=0,scale=2,size=(3,5))
a1
a1[:,[0,2,3]]

array([[ 2.51979265, -1.52658211,  0.26552386,  1.07724695, -1.9593886 ],
       [ 2.26377147, -2.76473237,  0.20164795, -1.66344836,  0.94653278],
       [-0.0940263 ,  1.71998137, -1.22421315,  1.51239967, -0.62271211]])

array([[ 2.51979265,  0.26552386,  1.07724695],
       [ 2.26377147,  0.20164795, -1.66344836],
       [-0.0940263 , -1.22421315,  1.51239967]])

In [28]:
a1=np.random.normal(0,2,size=(3,5))
a1
a1[:,[0,2,3]]

array([[ 0.05474591,  1.97542465, -1.96363788,  1.56218858, -1.16946107],
       [-2.50929706, -2.47396171,  1.31228711, -2.66422712,  2.39912103],
       [ 2.67381685,  1.48691564, -0.41799442, -2.45412729,  0.26118748]])

array([[ 0.05474591, -1.96363788,  1.56218858],
       [-2.50929706,  1.31228711, -2.66422712],
       [ 2.67381685, -0.41799442, -2.45412729]])

### 실습7

In [29]:
a1=np.random.randint(10,16,size=(4,2,3))
a1
a1[2,:,:]
a1[1::2,:,:]
a1[[1,3],:,:]

array([[[15, 14, 10],
        [12, 11, 12]],

       [[12, 14, 10],
        [11, 12, 12]],

       [[15, 10, 13],
        [14, 12, 15]],

       [[10, 10, 10],
        [14, 15, 10]]])

array([[15, 10, 13],
       [14, 12, 15]])

array([[[12, 14, 10],
        [11, 12, 12]],

       [[10, 10, 10],
        [14, 15, 10]]])

array([[[12, 14, 10],
        [11, 12, 12]],

       [[10, 10, 10],
        [14, 15, 10]]])

In [31]:
a1=np.random.randint(10,16,size=(4,2,3))
a1
a1[1]

array([[[13, 13, 11],
        [13, 11, 11]],

       [[15, 15, 10],
        [15, 14, 13]],

       [[10, 10, 12],
        [15, 13, 10]],

       [[12, 13, 15],
        [10, 13, 12]]])

array([[15, 15, 10],
       [15, 14, 13]])