In [1]:
import sys
print('python', sys.version)

import numpy as np
print('numpy', np.__version__)

import pandas as pd
print('pandas', pd.__version__)

import matplotlib.pyplot as plt

# 결과 확인을 용이하게 하기 위한 코드
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
numpy 1.20.3
pandas 1.3.4


In [3]:
a1=np.arange(10,16).reshape(2,3)
a2=np.arange(20,26).reshape(2,3)
a1
a2
a1+a2
a1-a2
a1*a2
a1/a2

array([[10, 11, 12],
       [13, 14, 15]])

array([[20, 21, 22],
       [23, 24, 25]])

array([[30, 32, 34],
       [36, 38, 40]])

array([[-10, -10, -10],
       [-10, -10, -10]])

array([[200, 231, 264],
       [299, 336, 375]])

array([[0.5       , 0.52380952, 0.54545455],
       [0.56521739, 0.58333333, 0.6       ]])

### 실습1

In [2]:
a1=np.arange(4,41,4)
a1
a2=a1*a1
a2
a2.sum()

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

array([  16,   64,  144,  256,  400,  576,  784, 1024, 1296, 1600])

6160

In [4]:
a1=np.arange(4,41,4)
a2=a1*a1
a2
np.sum(a2)

array([  16,   64,  144,  256,  400,  576,  784, 1024, 1296, 1600])

6160

#### broadcasting

In [8]:
a1=np.arange(10,16).reshape(2,3)
a1
a1+2
a1-2
a1*2
a1/2

array([[10, 11, 12],
       [13, 14, 15]])

array([[12, 13, 14],
       [15, 16, 17]])

array([[ 8,  9, 10],
       [11, 12, 13]])

array([[20, 22, 24],
       [26, 28, 30]])

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5]])

### 실습2

In [5]:
a1=np.arange(0,51,5)
a1
a2=a1%3
a2.sum()

s1=0
for i in range(51):
    if i%5==0:
        v1=i%3
        s1+=v1
s1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

11

11

In [8]:
a1=np.arange(0,51,5)
a1
a2=np.sum(a1%3)
a2

s1=0
for i in range(51):
    if i%5==0:
        v1=i%3
        s1+=v1
s1        

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

11

11

### 실습3

In [9]:
a1=np.arange(15).reshape(3,5)
a1

a1[0,:]+2
a1[1,:]+3
a1[2,:]+1

a2=np.array([2,3,1]).reshape(3,1)
a1+a2

a3=np.random.randint(10,size=(3,1))
a3
a1+a3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([2, 3, 4, 5, 6])

array([ 8,  9, 10, 11, 12])

array([11, 12, 13, 14, 15])

array([[ 2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12],
       [11, 12, 13, 14, 15]])

array([[0],
       [8],
       [2]])

array([[ 0,  1,  2,  3,  4],
       [13, 14, 15, 16, 17],
       [12, 13, 14, 15, 16]])

In [12]:
a1=np.arange(15).reshape(3,5)
a1[0,:]+2
a1[1,:]+3
a1[2,:]+1
a1

array([2, 3, 4, 5, 6])

array([ 8,  9, 10, 11, 12])

array([11, 12, 13, 14, 15])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
a1=np.arange(4)
a2=np.arange(10,15)
a3=np.concatenate((a1,a2))
a3

array([ 0,  1,  2,  3, 10, 11, 12, 13, 14])

In [29]:
a1=np.arange(12).reshape(4,3)
a1
a2=np.arange(8).reshape(4,2)
a2
a3=np.concatenate((a1,a2),axis=1)
a3
a3.shape

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [ 9, 10, 11,  6,  7]])

(4, 5)

### 실습4

In [13]:
a1=np.arange(1,4).reshape(1,3)
a2=np.concatenate((a1,a1,a1),axis=0)
a2
a2.shape
a3=a1.reshape(3,1)
a4=np.concatenate((a2,a3),axis=1)
a4

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

(3, 3)

array([[1, 2, 3, 1],
       [1, 2, 3, 2],
       [1, 2, 3, 3]])

In [16]:
a1=np.array([1,2,3]).reshape(1,3)
a2=np.concatenate((a1,a1,a1),axis=0)
a2
a3=a1.reshape(3,1)
a4=np.concatenate((a2,a3),axis=1)
a4

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

array([[1, 2, 3, 1],
       [1, 2, 3, 2],
       [1, 2, 3, 3]])

### 실습5

In [17]:
a1=np.random.randint(1,6,size=(3,4))
a1
a2=np.sqrt(a1)
a2
a2.sum()

array([[3, 2, 2, 3],
       [5, 4, 2, 2],
       [1, 4, 1, 4]])

array([[1.73205081, 1.41421356, 1.41421356, 1.73205081],
       [2.23606798, 2.        , 1.41421356, 1.41421356],
       [1.        , 2.        , 1.        , 2.        ]])

19.357023842129927

In [18]:
a1=np.random.randint(1,6,size=(3,4))
a1
a2=np.sqrt(a1)
np.sum(a2)

array([[4, 3, 5, 1],
       [3, 3, 4, 2],
       [2, 4, 3, 3]])

20.724749140090367

### 실습6

In [50]:
a1=np.random.randint(1,6,size=(3,4))
a1
m=a1.mean(axis=1)
s=a1.std(axis=1)
m=m.reshape(3,1)
s=s.reshape(3,1)

r1=(a1-m)/s
r1

array([[3, 1, 3, 3],
       [1, 2, 5, 4],
       [1, 2, 4, 5]])

array([[ 0.57735027, -1.73205081,  0.57735027,  0.57735027],
       [-1.26491106, -0.63245553,  1.26491106,  0.63245553],
       [-1.26491106, -0.63245553,  0.63245553,  1.26491106]])

#### Comparison

In [54]:
a1=np.random.randint(1,11,size=(2,3))
a2=np.random.randint(1,11,size=(2,3))
a1
a2
a1==a2
a3=(a1>a2)
a3
a3.sum()

array([[9, 5, 9],
       [8, 5, 2]])

array([[7, 9, 3],
       [5, 8, 1]])

array([[False, False, False],
       [False, False, False]])

array([[ True, False,  True],
       [ True, False,  True]])

4

### 실습7

In [57]:
a1=np.random.randint(1,11,size=(3,4))
a1
a2=(a1%3==0)
a2
a2.sum()

a1=np.random.randint(1,11,size=(3,4))
a1
a2=(a1%3==0)
a2
a2.sum(axis=1)

array([[10,  8,  7,  8],
       [ 1, 10,  8,  5],
       [ 9,  8,  2,  6]])

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False,  True]])

2

array([[5, 3, 3, 4],
       [6, 9, 2, 5],
       [7, 3, 8, 4]])

array([[False,  True,  True, False],
       [ True,  True, False, False],
       [False,  True, False, False]])

array([2, 2, 1])

In [ ]:
a1=np.r