In [1]:
import sys
print('python', sys.version)

import numpy as np
print('numpy', np.__version__)

import pandas as pd
print('pandas', pd.__version__)

import matplotlib.pyplot as plt

# 결과 확인을 용이하게 하기 위한 코드
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
numpy 1.20.3
pandas 1.3.4


In [9]:
a1=np.random.randint(100,size=(3,4))
a1
a2=(a1+10)>50
a3=(a1%2==0)
a2
a3
~a3
a2.sum()
print(a2&a3)
np.sum(a2&a3)

array([[40, 96,  7,  4],
       [14, 97, 37, 38],
       [82, 99, 95, 98]])

array([[False,  True, False, False],
       [False,  True, False, False],
       [ True,  True,  True,  True]])

array([[ True,  True, False,  True],
       [ True, False, False,  True],
       [ True, False, False,  True]])

array([[False, False,  True, False],
       [False,  True,  True, False],
       [False,  True,  True, False]])

6

[[False  True False False]
 [False False False False]
 [ True False False  True]]


3

### 실습1

In [2]:
a1=np.arange(4,41,4)
a1
a2=a1*a1
a2
a3=(a2%6==0)
a3
a3.sum()

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

array([  16,   64,  144,  256,  400,  576,  784, 1024, 1296, 1600])

array([False, False,  True, False, False,  True, False, False,  True,
       False])

3

In [3]:
a1=np.arange(4,41,4)
a1
a2=a1*a1
a2
a3=np.sum(a2%6==0)
a3

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

array([  16,   64,  144,  256,  400,  576,  784, 1024, 1296, 1600])

3

In [4]:
a1=np.arange(4,41,4)
a1
a2=a1*a1
a2
a3=np.sum((a2%6==0))
a3

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

array([  16,   64,  144,  256,  400,  576,  784, 1024, 1296, 1600])

3

### 실습2

In [5]:
a1=np.random.randint(1,11,size=(3,3))
a1
a2=a1!=6
a3=(a1%3==0)
a4=(a2&a3)
a4
a4.sum()

array([[ 2, 10,  4],
       [ 9,  9,  4],
       [ 8, 10, 10]])

array([[False, False, False],
       [ True,  True, False],
       [False, False, False]])

2

In [6]:
a1=np.random.randint(1,11,size=(3,3))
a1
a2=a1!=7
a2
a3=(a1%3==0)
a3
a4=np.sum(a2&a3)
a4

array([[3, 1, 6],
       [9, 1, 4],
       [7, 8, 1]])

array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

array([[ True, False,  True],
       [ True, False, False],
       [False, False, False]])

3

In [5]:
a1=np.random.randint(1,11,size=(3,3))
a1
a2=(a1!=6)&(a1%3==0)
a2
np.sum(a2)

array([[10, 10,  1],
       [ 4,  9,  1],
       [10,  6,  3]])

array([[False, False, False],
       [False,  True, False],
       [False, False,  True]])

2

#### np.nan

In [7]:
a1=np.array([1,np.nan,2,np.nan,3])
a1
a1==a1 # nan이 아닌 값은 같다면 True
a1==np.nan # 동작X
np.isnan(a1)
~np.isnan(a1)

array([ 1., nan,  2., nan,  3.])

array([ True, False,  True, False,  True])

array([False, False, False, False, False])

array([False,  True, False,  True, False])

array([ True, False,  True, False,  True])

In [10]:
a1=np.array([1,np.nan,2,np.nan,3])
a1
a1==a1
np.isnan(a1)
~np.isnan(a1)

array([ 1., nan,  2., nan,  3.])

array([ True, False,  True, False,  True])

array([False,  True, False,  True, False])

array([ True, False,  True, False,  True])

#### np.where

In [11]:
a=np.array([150,100,20,0])
a
np.where(a>50,'A','B')

array([150, 100,  20,   0])

array(['A', 'A', 'B', 'B'], dtype='<U1')

In [12]:
b=np.array([200,300,100,9])
b
np.where(b>0,1,0)

array([200, 300, 100,   9])

array([1, 1, 1, 1])

In [13]:
a=np.arange(100,110)
a
b=np.where(a%2==0)
b
type(b)
b=b[0]
b
type(b)

a=np.arange(100,110).reshape(2,5)
a
b=np.where(a%2==0)
b
type(b)
b0=b[0]
b1=b[1]
type(b1)
b1
list(zip(b0,b1))

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

(array([0, 2, 4, 6, 8], dtype=int64),)

tuple

array([0, 2, 4, 6, 8], dtype=int64)

numpy.ndarray

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109]])

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 2, 4, 1, 3], dtype=int64))

tuple

numpy.ndarray

array([0, 2, 4, 1, 3], dtype=int64)

[(0, 0), (0, 2), (0, 4), (1, 1), (1, 3)]

### 실습3

In [6]:
a1=np.random.randint(1,11,size=(5,5))
a1
a2=np.where(a1>=7)
a3=np.where((a1>=7)&(a1%2==0))
a2
a3

s1=0
for i,j in zip(a2[0],a2[1]):
    s1+=a1[i,j]
s1

s2=0
for ii,jj in zip(a3[0],a3[1]):
    s2+=a1[ii,jj]
s2


array([[ 2,  5,  6, 10,  1],
       [ 7,  6,  6,  4,  2],
       [ 1,  8,  9,  1,  5],
       [ 1,  7,  8,  8, 10],
       [ 7,  8,  8,  4,  7]])

(array([0, 1, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4], dtype=int64),
 array([3, 0, 1, 2, 1, 2, 3, 4, 0, 1, 2, 4], dtype=int64))

(array([0, 2, 3, 3, 3, 4, 4], dtype=int64),
 array([3, 1, 2, 3, 4, 1, 2], dtype=int64))

97

60

In [14]:
a1=np.random.randint(1,11,size=(5,5))
a1
a2=np.where(a1>=7)
a2
s1=0
for i,j in zip(a2[0],a2[1]):
    s1+=a1[i,j]
s1

array([[ 6,  1, 10,  9,  5],
       [ 6,  5,  3, 10,  9],
       [10,  1,  9,  2,  2],
       [ 7,  6, 10,  1,  1],
       [ 8,  9,  8,  8,  1]])

(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 4, 4], dtype=int64),
 array([2, 3, 3, 4, 0, 2, 0, 2, 0, 1, 2, 3], dtype=int64))

107

In [15]:
a1=np.random.randint(1,11,size=(5,5))
a1
a2=np.where((a1>=7)&(a1%2==0))
a2

s1=0
for i,j in zip(a2[0],a2[1]):
    s1+=a1[i,j]
s1

array([[ 4,  5,  1,  4,  4],
       [ 6, 10,  3, 10,  3],
       [ 5,  2,  3,  2,  6],
       [ 2,  5,  7, 10,  4],
       [10,  9,  4,  3,  7]])

(array([1, 1, 3, 4], dtype=int64), array([1, 3, 3, 0], dtype=int64))

40

#### Boolean Index

In [16]:
a1=np.random.randint(1,11,size=(2,4))
a1
a1<=3
a1[a1<=3]

array([[10,  6,  3,  2],
       [ 6,  9,  5, 10]])

array([[False, False,  True,  True],
       [False, False, False, False]])

array([3, 2])

In [17]:
a1=np.random.randint(1,11,size=(2,4))
a1
a1[a1<=4]

array([[10,  3,  6,  8],
       [ 2,  7,  9,  8]])

array([3, 2])

In [18]:
a1=np.random.randint(10,size=(3,3))
a1
a2=a1[a1%3!=0]
a2

array([[0, 8, 4],
       [7, 2, 6],
       [3, 2, 2]])

array([8, 4, 7, 2, 2, 2])

In [19]:
a1=np.random.randint(10,size=(3,3))
a1
a1[a1%3!=0]

array([[6, 2, 7],
       [1, 4, 8],
       [6, 2, 6]])

array([2, 7, 1, 4, 8, 2])

In [38]:
a1=np.random.randint(1,11,size=(3,4))
a2=np.random.randint(1,11,size=(3,4))
a1
a2
a2[a1>5]

array([[ 6, 10,  2,  3],
       [10,  8,  7,  6],
       [ 2,  2,  6,  6]])

array([[ 3,  6,  9,  7],
       [ 6, 10,  8,  9],
       [10,  6,  4,  8]])

array([ 3,  6,  6, 10,  8,  9,  4,  8])

In [20]:
a1=np.random.randint(100,size=(3,4))
a1
a1[[True,False,False],:]
a1[:,[True,False,False,True]]

array([[52, 74, 62, 31],
       [12, 43, 87, 31],
       [40,  4, 83, 52]])

array([[52, 74, 62, 31]])

array([[52, 31],
       [12, 31],
       [40, 52]])

In [22]:
a1=np.random.randint(100,size=(3,4))
a1
a1[:,[True,False,False,True]]

array([[69, 83, 13,  3],
       [25,  2, 62, 44],
       [52, 59, 44, 72]])

array([[69,  3],
       [25, 44],
       [52, 72]])

### 실습4

In [9]:
a1=np.arange(24).reshape(6,4)
a1
a2=a1[:,3]
a2
b1=(a2%3==0)|(a2>10)
b1
a3=a2[b1]
a3
a3.sum()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

array([ 3,  7, 11, 15, 19, 23])

array([ True, False,  True,  True,  True,  True])

array([ 3, 11, 15, 19, 23])

71

In [23]:
a1=np.arange(24).reshape(6,4)
a1
a2=a1[:,2]
a3=(a2%3==0)|(a2>10)
np.sum(a2[a3])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

60

In [26]:
a1=np.arange(24).reshape(6,4)
a1
a2=a1[:,2]
a2
a3=(a2%3==0)|(a2>10)
a3
np.sum(a2[a3])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

array([ 2,  6, 10, 14, 18, 22])

array([False,  True, False,  True,  True,  True])

60

### 실습5

In [14]:
a1=np.random.randint(10,size=(5,5))
a1
a2=a1[:,4]
a2
b1=(a2>5)
b1
b2=a1[b1,:]
b2
b2.mean(axis=1)

array([[4, 4, 5, 2, 3],
       [4, 2, 9, 9, 4],
       [9, 7, 0, 7, 2],
       [6, 1, 1, 5, 2],
       [0, 5, 6, 7, 7]])

array([3, 4, 2, 2, 7])

array([False, False, False, False,  True])

array([[0, 5, 6, 7, 7]])

array([5.])

In [27]:
a1=np.random.randint(10,size=(5,5))
a1
a2=a1[:,-1]
a3=(a2>5)
a3
a4=a1[a3,:]
a4.mean(axis=1)

array([[1, 6, 5, 2, 3],
       [1, 4, 0, 7, 2],
       [1, 8, 3, 4, 2],
       [2, 7, 7, 2, 4],
       [5, 1, 0, 2, 1]])

array([False, False, False, False, False])

array([], dtype=float64)

In [31]:
a1=np.random.randint(10,size=(5,5))
a1
a2=a1[1,:]
a2
a3=(a2>4)
a3
a4=a1[a3,:].mean(axis=1)
a4
a4.dtype

array([[5, 5, 1, 6, 1],
       [9, 8, 8, 2, 7],
       [1, 7, 7, 0, 0],
       [6, 9, 7, 7, 9],
       [9, 9, 6, 0, 3]])

array([9, 8, 8, 2, 7])

array([ True,  True,  True, False,  True])

array([3.6, 6.8, 3. , 5.4])

dtype('float64')

### 실습6

In [19]:
math=np.random.randint(10,size=10)
print(math)
engl=np.random.randint(10,size=10)
print(engl)

a1=(math<engl)
a1
a1.sum()

a2=math[a1]
a2
a2.mean()

[6 2 2 6 3 5 3 8 4 9]
[3 5 9 3 2 5 0 8 4 5]


array([False,  True,  True, False, False, False, False, False, False,
       False])

2

array([2, 2])

2.0

In [25]:
math=np.random.randint(10,size=10)
print(math)
engl=np.random.randint(10,size=10)
print(engl)

a1=np.sum(math<engl)
a1
a2=(math<engl)
a3=np.mean(math[a2])
a3

[4 1 3 9 8 5 2 7 5 1]
[2 5 1 8 3 3 8 3 0 4]


3

1.3333333333333333

#### Fancy Index

In [66]:
a1=np.array([1,2,3,4])
index=np.array([0,0,3,2])
a1[index]

array([1, 1, 4, 3])

In [67]:
a1=np.random.randint(100,size=(4,5))
a1
a1[[0,1,2],[2,3,2]]

array([[85, 58, 74, 51, 82],
       [10, 89, 42, 88, 33],
       [19, 64, 48, 96, 45],
       [35, 16, 12, 51, 62]])

array([74, 88, 48])

In [32]:
a1=np.random.randint(100,size=(4,5))
a1
b1=np.where(a1>70)
b1
b2=a1[b1]
b2

array([[29, 88, 19, 21, 40],
       [72,  0, 32, 61, 57],
       [39, 18, 45, 90, 13],
       [17,  6, 71, 44, 94]])

(array([0, 1, 2, 3, 3], dtype=int64), array([1, 0, 3, 2, 4], dtype=int64))

array([88, 72, 90, 71, 94])

In [35]:
a1=np.random.randint(100,size=(4,5))
a1
b1=np.where(a1>70)
b1
b2=a1[b1]
b2
for i,j in zip(b1[0],b1[1]):
    [i,j]

array([[48, 85, 44, 24, 50],
       [31, 60, 23, 63,  6],
       [70, 25, 43, 35,  9],
       [66, 43, 97, 79,  9]])

(array([0, 3, 3], dtype=int64), array([1, 2, 3], dtype=int64))

array([85, 97, 79])

[0, 1]

[3, 2]

[3, 3]

### 실습7

In [26]:
a1=np.array([1000,2000,1500,2000])
a2=np.array([1,1,3,2,2,3,4,1])
a3=a1[a2-1]
a3
a3.sum()

array([1000, 1000, 1500, 2000, 2000, 1500, 2000, 1000])

12000

In [29]:
a1=np.array([1000,2000,1500,2000])
a2=np.array([1,1,3,2,2,3,4,1])
a3=a1[a2-1]
a3.sum()

12000

### 실습8

In [30]:
a1=np.random.randint(10,size=(6,4))
a1=a1.astype(float)
a1[[0,1,1,3],[1,1,2,3]]=np.nan
a1
# a2=~np.isnan(a1)
# a2
# a3=a1[a2]
# a3
np.isnan(a1)
a2=np.isnan(a1).sum(axis=1)
b1=(a2==0)
a1[b1,:]

array([[ 5., nan,  8.,  1.],
       [ 6., nan, nan,  5.],
       [ 1.,  7.,  2.,  2.],
       [ 1.,  4.,  0., nan],
       [ 5.,  7.,  1.,  2.],
       [ 8.,  3.,  0.,  8.]])

array([[False,  True, False, False],
       [False,  True,  True, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

array([[1., 7., 2., 2.],
       [5., 7., 1., 2.],
       [8., 3., 0., 8.]])

In [33]:
a1=np.random.randint(10,size=(6,4))
a1=a1.astype(float)
a1[[0,1,1,3],[1,1,2,3]]=np.nan
a1
a2=np.isnan(a1).sum(axis=1)
a2
a3=(a2==0)
a1[a3,:]

array([[ 0., nan,  6.,  0.],
       [ 4., nan, nan,  5.],
       [ 1.,  3.,  5.,  7.],
       [ 3.,  6.,  4., nan],
       [ 3.,  6.,  6.,  3.],
       [ 9.,  8.,  0.,  8.]])

array([1, 2, 0, 1, 0, 0])

array([[1., 3., 5., 7.],
       [3., 6., 6., 3.],
       [9., 8., 0., 8.]])

### 문제1

In [88]:
a1=np.random.randint(10,size=(6,4))
a1=a1.astype(float)
a1[[0,2,2,5],[1,1,3,3]]=np.nan
a1
np.isnan(a1)
a2=np.isnan(a1).sum(axis=0)
a2
b1=(a2==0)
a1[:,b1].min(axis=0)

array([[ 0., nan,  4.,  3.],
       [ 2.,  8.,  3.,  9.],
       [ 9., nan,  2., nan],
       [ 8.,  3.,  0.,  2.],
       [ 6.,  4.,  5.,  7.],
       [ 5.,  0.,  1., nan]])

array([[False,  True, False, False],
       [False, False, False, False],
       [False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

array([0, 2, 0, 2])

array([0., 0.])

### 문제2

In [96]:
a1=np.random.randint(10,size=(3,5))
a1
m=a1[0]
m
e=a1[1]
e
g=a1[2]
g
b1=(m>e)
b1
g[b1].sum()

array([[6, 8, 4, 4, 0],
       [5, 6, 0, 3, 8],
       [9, 5, 4, 5, 5]])

array([6, 8, 4, 4, 0])

array([5, 6, 0, 3, 8])

array([9, 5, 4, 5, 5])

array([ True,  True,  True,  True, False])

23

### 문제3

In [100]:
a1=np.random.randint(1,11,size=(3,4))
a1
a2=a1.mean(axis=0)
a2
np.sum(a1>a2,axis=0)

array([[ 6,  5,  6, 10],
       [ 1,  7,  7, 10],
       [ 9,  6,  5,  5]])

array([5.33333333, 6.        , 6.        , 8.33333333])

array([2, 1, 1, 2])

### 문제4

In [102]:
a1=np.random.randint(1,11,size=(3,4))
a1
m=a1.mean(axis=0)
s=a1.std(axis=0)
np.sum(a1>m-s,axis=0)

array([[ 5,  9,  8,  6],
       [ 8,  7,  6,  7],
       [ 9,  6,  6, 10]])

array([2, 2, 3, 3])