### 과제1-1

In [17]:
import numpy as np

# 1)
print('### 1) ####')
# == 코드작성 ==

ar1=([[1,2],[3,4]])
ar2=np.array([ar1,ar1,ar1],np.int16)
ar2

### 1) ####


array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]], dtype=int16)

In [18]:
ar2.dtype

dtype('int16')

In [19]:
# 2)
print('### 2) ####')
# == 코드작성 ==

ar1=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]],np.int16)
ar2=ar1.reshape(3,2,2)
ar2

### 2) ####


array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]], dtype=int16)

In [21]:
ar2.dtype

dtype('int16')

### 과제1-2

In [24]:
# == 코드 작성 ==

In [22]:
ar1=np.array([[1,2,3],[4,5,6000]],np.int8)
ar1

array([[  1,   2,   3],
       [  4,   5, 112]], dtype=int8)

In [30]:
ar2=np.array([[1,2,3],[4,5,6000]],np.int32)
ar2

array([[   1,    2,    3],
       [   4,    5, 6000]])

##### int32가 적합합니다.
##### 이유: int32가 int8보다 메모리 크기가 크기 때문에 6000까지 bits값을 나타내는 데에 더 효율적이기 때문입니다.